version: '3'

services:
  postgres:
    image: postgres:15.2
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"

  backend:
    image: diplom:latest
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres